#+title: Readme for fkl21's Minidox Configuration

* About
  This is includes notes about my personal Minidox configuration.
  To put it in a nutshell, dustypomerleau layout was modified until it was 'right' and
  this is the current result.

* Changes
** TODO add changes here.

* Adapt this layout for my needs
* Tasks:
  NOTE: other tasks are in source code [[file:keymap.c][keymap.c]]
** CANCELLED swap SYM/OS (middle thumbcluster key) with most inner ones i.e. NAV/BK and NUM/SP
   CLOSED: [2020-03-23 Mo 14:28]
** DONE remap ";" to original qerty layout position
   CLOSED: [2020-03-23 Mo 14:28]
*** DONE SFT (Shift) needs to be placed onto ";"
   CLOSED: [2020-03-23 Mo 14:28]
* Notes:
** Dual-Use-Key Repetition: when pressing key twice and keep pressing down, then key is repeated
*** this works with all keys e.g. j k l h for vim, space, del, etc.

* dustypomerleau, Minidox layout (this is the original README)

  The rationale behind my layout can be summarized as follows:

  - Symmetry is important because use-cases are hard to predict. Whenever possible, modifiers and layer keys should be available from either hand.
  - Inward rolls should be leveraged not just for alphas (Colemak DHm), but also for coding/symbols.
  - Number order—like alpha order—should be designed to favor use of the strongest fingers.
  - One-shot keys can greatly reduce the strain of typing, and should be leveraged.

  Some aspects of my layout are optimized for macOS (order of modifiers, manner of producing en and em dashes, coding of micro-volume adjustments, etc.), but can be easily tweaked for the OS of your choice.

  Shift can be a tricky modifier when used in `MT()` combinations, particularly for fast typists on split boards using serial. This can be partially mitigated with options in `config.h`, but still requires a relatively strict typing style/accuracy from the fast typist. The tendency is for faster typists to combat mod/tap mistakes by using very short intervals for `TAPPING_TERM`, but this can introduce its own set of complications. Shift is also one of the highest-yield opportunities to use `OSM()`. For these reasons, I pulled Shift onto dedicated keys in the thumbs for use during regular typing (the home row Shifts have been left in place for use during selection and keycuts).

  The tapdance code that I used to create mod/tap keys inside my symbol layer allows up to 2 consecutive symbols within `TAPPING_TERM`. If you think you will need to quickly nest more than that, feel free to add more `case`s.

** Special thanks

   - Everyone on the QMK Discord, for helping me work out the code for mod/tap keys using shifted symbols.
   - Everyone on the Colemak Discord, for their initial feedback on the layout.
   - @stevep and @DreymaR, for their work on Colemak DH(m), a truly awesome typing experience (and of course Shai Coleman, for starting it all off!).
   - @ckofy, for offering a dramatic improvement on Dvorak's original number order.
   - u/That-Canadian, for designing this awesome keyboard.

** Questions or comments?

   - GitHub @dustypomerleau
   - Twitter @duspom
   - Discord @dusty#8897
* OLD
** Predefined Layouts
*** Tested ones:
**** dustypomerleau
***** interesting bc of dual use of a s d f and j k l ; for shift, control, alt, super
**** dustypomerleau
***** Lookes quite like default
** Features
*** To Try:
**** TODO dustypomerleau Shift/Ctrl/Alt/Super on a s d f  and ; l k j
***** this is kind of nice, but for vim holding j k l h to move is not possible
**** TODO copy from already existing layout
*** To Use:
*** That don't work properly:

** Notes
*** Key-Layout:
**** Layer 0
     from alairock
     /* Qwerty
      *
      * ,----------------------------------.           ,----------------------------------.
      * |   Q  |   W  |   E  |   R  |   T  |           |   Y  |   U  |   I  |   O  |   P  |
      * |------+------+------+------+------|           |------+------+------+------+------|
      * |   A  |   S  |   D  |   F  |   G  |           |   H  |   J  |   K  |   L  |   ;  |
      * |------+------+------+------+------|           |------+------+------+------+------|
      * |   Z  |   X  |   C  |   V  |   B  |           |   N  |   M  |   ,  |   .  |   /  |
      * `----------------------------------'           `----------------------------------'
      *                  ,--------------------.    ,------,-------------.
      *                  | Shift/Esc | GUI/Tab|    |      | RAISE| LOWER |
      *                  `-------------|BSpace|    |Space |------+------.
      *                                |      |    |      |
      *                                `------'    `------'


** Layout Notes
* Lost+Found
** Empty Layer-Template:
   /*
   *
   * ,----------------------------------.           ,----------------------------------.
   * |      |      |      |      |      |           |      |      |      |      |      |
   * |------+------+------+------+------|           |------+------+------+------+------|
   * |      |      |      |      |      |           |      |      |      |      |      |
   * |------+------+------+------+------|           |------+------+------+------+------|
   * |      |      |      |      |      |           |      |      |      |      |      |
   * `----------------------------------'           `----------------------------------'
   *                  ,--------------------.    ,------,-------------.
   *                  |           |        |    |      |      |       |
   *                  `-------------|      |    |      |------+------.
   *                                |      |    |      |
   *                                `------'    `------'
