#+title: Readme for fkl21's Minidox Configuration

* About
  This is includes notes about this Minidox configuration.
  To put it in a nutshell, dustypomerleau layout was modified until it was 'right'
  for me and this is the current result.

* Changes
  - swap sym/os and num/sp on thumb-clusters
  - QWERTY: swap / and ;
  - vim-style for mouse and arrow keys + home page up and page down
  - add numblock instead of Dvorak-style number-layer
  - changed system-layer, navigation-layer, numbers/F-Keys/-layer
  - additional one-handed thumb-pinky combinations (normal usage requires both hands)
    - left: tab, esc and caps at leftmost column
    - right: enter rightmost middle key
  - available layouts are:
    - QWERTY
    - Colemak DHm
      Matrix "DHm": Colemak Mod-DH (Rev 1) for a non-staggered keyboard.
      Due to the geometry of this type of keyboard, you may prefer to
      switch the M and K keys as per the original Mod-DH release.
      This layout is also known as ‘Colemak-DHm’.
      [[https://colemakmods.github.io/mod-dh/keyboards.html][Implementation on Keyboard Types]]
    - [[https://www.neo-layout.org/][Neo2]]  added
    - Gaming added
      - basically a right-shifted QWERTY-layout
      - CTRL, SHIFT, TAB are where they 'normally' are
      - Second Layer maps some right keys and numbers to left half
      - Use QWERTY's 'y' of right-side to as sys-layer modifier in gaming mode
        (to return to another layer e.g. qwerty, neo2, colemak)
* Tasks:
  NOTE: other tasks are in source code [[file:keymap.c][keymap.c]]
  - TODO Umlaute are still missing (ae, oe ue, ss)
  - TODO rewrite all ALT_X, CTRL_X, GUI_X, SFT_X to ALT(x) [...] etc.
  - TODO add different toggle-able number layers e.g.
    - 1234567890 home row
    - even/odd home row (like dustypomerleau's)
    - different numblock-style
  - TODO add different toggle-able Symbol-Layer e.g.
    - NEO2-Syms-like: parentheses!
  - TODO add different toggle-able Navigation-Layer e.g.
    - reverse T shaped arrows (maybe like neo2)
* Notes:
** Dual-Use-Key Repetition: when pressing key twice and keep holding down, then key is repeated
** a,o as Shift keys is not optimal yet (see dustypomerleau's)



* dustypomerleau's README
  The rationale behind my layout can be summarized as follows:

  - Symmetry is important because use-cases are hard to predict. Whenever possible, modifiers and layer keys should be available from either hand.
  - Inward rolls should be leveraged not just for alphas (Colemak DHm), but also for coding/symbols.
  - Number order—like alpha order—should be designed to favor use of the strongest fingers.
  - One-shot keys can greatly reduce the strain of typing, and should be leveraged.

  Some aspects of my layout are optimized for macOS (order of modifiers, manner of producing en and em dashes, coding of micro-volume adjustments, etc.), but can be easily tweaked for the OS of your choice.

  Shift can be a tricky modifier when used in `MT()` combinations, particularly for fast typists on split boards using serial. This can be partially mitigated with options in `config.h`, but still requires a relatively strict typing style/accuracy from the fast typist. The tendency is for faster typists to combat mod/tap mistakes by using very short intervals for `TAPPING_TERM`, but this can introduce its own set of complications. Shift is also one of the highest-yield opportunities to use `OSM()`. For these reasons, I pulled Shift onto dedicated keys in the thumbs for use during regular typing (the home row Shifts have been left in place for use during selection and keycuts).

  The tapdance code that I used to create mod/tap keys inside my symbol layer allows up to 2 consecutive symbols within `TAPPING_TERM`. If you think you will need to quickly nest more than that, feel free to add more `case`s.

** Special thanks
   - Everyone on the QMK Discord, for helping me work out the code for mod/tap keys using shifted symbols.
   - Everyone on the Colemak Discord, for their initial feedback on the layout.
   - @stevep and @DreymaR, for their work on Colemak DH(m), a truly awesome typing experience (and of course Shai Coleman, for starting it all off!).
   - @ckofy, for offering a dramatic improvement on Dvorak's original number order.
   - u/That-Canadian, for designing this awesome keyboard.
** Questions or comments?
   - GitHub @dustypomerleau
   - Twitter @duspom
   - Discord @dusty#8897
